const products = [
  {
    id: 1,
    title: 'Black Backpack',
    brand: 'Wildcraft',
    price: 1199,
    category: 'Bags',
    image: 'https://picsum.photos/seed/bag1/300/300',
  },
  {
    id: 2,
    title: 'Toy Dinosaur',
    brand: 'ToyLand',
    price: 699,
    category: 'Toys',
    image: 'https://picsum.photos/seed/toy1/300/300',
  },
  {
    id: 3,
    title: 'Canvas Pouch',
    brand: 'StationX',
    price: 399,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/pouch1/300/300',
  },
  {
    id: 4,
    title: 'Printed T-Shirt',
    brand: 'Bewakoof',
    price: 599,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/shirt1/300/300',
  },
  {
    id: 5,
    title: 'Woolen Cap',
    brand: 'H&M',
    price: 299,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/cap1/300/300',
  },
  {
    id: 6,
    title: 'Denim Jeans',
    brand: 'Levi’s',
    price: 1899,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/jeans1/300/300',
  },
  {
    id: 7,
    title: 'Formal Shirt',
    brand: 'Van Heusen',
    price: 1499,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/formal1/300/300',
  },
  {
    id: 8,
    title: 'Elegant Dress',
    brand: 'Zara',
    price: 2499,
    category: 'Clothing',
    image: 'https://picsum.photos/seed/dress1/300/300',
  },
  {
    id: 9,
    title: 'Kid’s Hoodie',
    brand: 'BabyGap',
    price: 999,
    category: 'Kidswear',
    image: 'https://picsum.photos/seed/kid1/300/300',
  },
  {
    id: 10,
    title: 'Stylish Watch',
    brand: 'Fastrack',
    price: 1999,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/watch1/300/300',
  },
  {
    id: 11,
    title: 'Running Shoes',
    brand: 'Nike',
    price: 3299,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/shoes1/300/300',
  },
  {
    id: 12,
    title: 'Yoga Mat',
    brand: 'Decathlon',
    price: 799,
    category: 'Fitness',
    image: 'https://picsum.photos/seed/mat1/300/300',
  },
  {
  id: 13,
  title: 'Brown Leather Wallet',
  brand: 'Tommy Hilfiger',
  price: 899,
  category: 'Accessories',
  image: 'https://picsum.photos/seed/wallet1/300/300',
},
{
  id: 14,
  title: 'Portable Bluetooth Speaker',
  brand: 'boAt',
  price: 1599,
  category: 'Electronics',
  image: 'https://picsum.photos/seed/speaker1/300/300',
},
{
  id: 15,
  title: 'Classic Aviator Sunglasses',
  brand: 'Ray-Ban',
  price: 2999,
  category: 'Accessories',
  image: 'https://picsum.photos/seed/sunglasses1/300/300',
},
{
  id: 16,
  title: 'Titan Analog Watch',
  brand: 'Titan',
  price: 2499,
  category: 'Accessories',
  image: 'https://picsum.photos/seed/watch2/300/300',
},
{
  id: 17,
  title: 'White Casual Sneakers',
  brand: 'Adidas',
  price: 3399,
  category: 'Footwear',
  image: 'https://picsum.photos/seed/sneakers1/300/300',
},
{
  id: 18,
  title: 'Slim Laptop Sleeve',
  brand: 'AmazonBasics',
  price: 499,
  category: 'Bags',
  image: 'https://picsum.photos/seed/sleeve1/300/300',
},
{
  id: 19,
  title: 'Large Travel Duffel Bag',
  brand: 'American Tourister',
  price: 2299,
  category: 'Bags',
  image: 'https://picsum.photos/seed/duffel1/300/300',
},
{
  id: 20,
  title: 'Floral Print Women’s Kurti',
  brand: 'Biba',
  price: 1299,
  category: 'Clothing',
  image: 'https://picsum.photos/seed/kurti1/300/300',
},
{
  id: 21,
  title: 'Running Sports Shorts',
  brand: 'Nike',
  price: 799,
  category: 'Clothing',
  image: 'https://picsum.photos/seed/shorts1/300/300',
},
{
  id: 22,
  title: 'Compact Makeup Organizer',
  brand: 'Nykaa',
  price: 349,
  category: 'Accessories',
  image: 'https://picsum.photos/seed/makeup1/300/300',
},
{
  id: 23,
  title: 'Plush Dinosaur Toy',
  brand: 'Hamleys',
  price: 599,
  category: 'Toys',
  image: 'https://picsum.photos/seed/softtoy1/300/300',
},
{
  id: 24,
  title: 'Brown Ankle Boots',
  brand: 'Woodland',
  price: 2899,
  category: 'Footwear',
  image: 'https://picsum.photos/seed/boots1/300/300',
},

];

export default products;
